In [12]:
import torchaudio

In [27]:
data, sample_rate = torchaudio.load('/nfs1/shared/for_aniruddha/pose/dataset/audios/AaronKoblin_2011-480p_0005.mp3')

In [28]:
data.size(), sample_rate

(torch.Size([222308, 2]), 44100)

In [24]:
(44100*5 - 222308)/44100

-0.040997732426303855

In [29]:
test = torch.Tensor([1, 0, 1, 0, 1, 1, 1, 0])

In [30]:
test

tensor([ 1.,  0.,  1.,  0.,  1.,  1.,  1.,  0.])

In [31]:
x = test.long()

In [32]:
x 

tensor([ 1,  0,  1,  0,  1,  1,  1,  0])

In [33]:
x[x == 0] = -1

In [34]:
x

tensor([ 1, -1,  1, -1,  1,  1,  1, -1])

In [38]:
import torch.nn as nn
criterion = nn.CosineEmbeddingLoss()
a = torch.Tensor([1,-1])
b = torch.Tensor([-1,0.5])
label = torch.Tensor([-1])
loss = criterion(a,b,label)

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

In [40]:
a = [True, False, True]
sum(a)

2